---
title: "Teens and Tech Exploratory Data Analysis (EDA)"
author: "Jennifer Truong"
date: "2023-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages ----
library(tidyverse)
library(janitor) # for data cleaning
library(here) # for easier file path reading
library(archive) # for interacting with ZIP files

```

```{r Exploring zip files with raw data}

# Uncomment code lines if doing this for the first time

# Explore structure of raw data ----

# First, let's see what's in the zip files

# This dataset has 5 files
# The one we want is "September 25-October 9, 2014 and February 10-March 6, 2015 - Teens/September 25-October 9, 2014 and February 10-March 6, 2015 - Teens - CSV.csv"

# archive(here("raw_data/September-25-October-9-2014-and-February-10-March-6-2015-Teens.zip"))

# This zip file also has 5 datasets
# The one we want is "March 7-April 10, 2018 - Teens and Tech Survey - CSV.csv"

# archive(here("raw_data/March-7-April-10-2018-Teens-and-Tech-Survey.zip"))

# Extract CSVs from zip files ----

# archive_extract(here("raw_data/September-25-October-9-2014-and-February-10-March-6-2015-Teens.zip"), dir = here("raw_data"), files = ("September 25-October 9, 2014 and February 10-March 6, 2015 - Teens/September 25-October 9, 2014 and February 10-March 6, 2015 - Teens - CSV.csv"))

# archive_extract(here("raw_data/March-7-April-10-2018-Teens-and-Tech-Survey.zip"), dir = here("raw_data"), files = ("March 7-April 10, 2018 - Teens and Tech Survey - CSV.csv"))

```

## Exploring the data structure

```{r Load CSVs into RStudio}

teens_2014_2015 <- read_csv(here("raw_data/September 25-October 9, 2014 and February 10-March 6, 2015 - Teens/September 25-October 9, 2014 and February 10-March 6, 2015 - Teens - CSV.csv"))

teens_2018 <- read_csv(here("raw_data/March 7-April 10, 2018 - Teens and Tech Survey - CSV.csv"))

```
At first glance, these datasets seem very messy. I should visit the original data source to learn more.
